name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'  # uruchamia się przy puszczeniu taga np. v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: List APK files
        run: ls -l app/build/outputs/apk/release/

      - name: Run Unit Tests
        run: ./gradlew testReleaseUnitTest

      - name: Create or Update GitHub Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: app/build/outputs/apk/release/app-release.apk  # <- zaktualizuj, jeśli inna nazwa pliku
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
