name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Debug APK existence
        run: find app/build/outputs -type f -name "*.apk"

      - name: Upload APK as artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-debug
          path: app/build/outputs/apk/release/*.apk

      - name: Run Unit Tests
        run: ./gradlew testReleaseUnitTest

      - name: Create or Update GitHub Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: app/build/outputs/apk/release/*.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
